version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: listings_postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: cmcs03w7c000007jl2v8jevqq
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - listings_network
    restart: unless-stopped

  listings-service:
    build: .
    container_name: listings_service
    depends_on:
      - postgres
    networks:
      - listings_network
    volumes:
      - ./configs:/root/configs
    environment:
      - TZ=America/Toronto
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  adminer:
    image: adminer
    container_name: listings_adminer
    ports:
      - "8080:8080"
    networks:
      - listings_network
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  listings_network:
    driver: bridge