version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: listings_postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: cmcs03w7c000007jl2v8jevqq
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - listings_network

  redis:
    image: redis:7-alpine
    container_name: listings_redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    networks:
      - listings_network

  adminer:
    image: adminer
    container_name: listings_adminer
    ports:
      - "8080:8080"
    networks:
      - listings_network
    depends_on:
      - postgres

volumes:
  postgres_data:
  redis_data:

networks:
  listings_network:
    driver: bridge