services:
  postgres:
    image: postgres:16-alpine
    container_name: listings_postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: listings_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  listings-api:
    build:
      context: ./listings-api
    container_name: listings_api
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    environment:
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=password
      - DATABASE_NAME=postgres
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
      - ENVIRONMENT=development
      - DEBUG=true
      - ALLOWED_ORIGINS=http://localhost:3000,http://localhost:8000,http://localhost:8080

  listings-ingestion:
    build: 
      context: ./listings-service
    container_name: listings_ingestion
    depends_on:
      - postgres
    volumes:
      - ./simple-config.yml:/app/configs/config.yml
    environment:
      - RUN_ONCE=true

  adminer:
    image: adminer
    container_name: listings_adminer
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  postgres_data:
  redis_data: