# Production Environment
services:
  postgres:
    image: postgres:16-alpine
    container_name: listings_postgres_prod
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: listings_redis_prod
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  listings-api:
    build:
      context: ./listings-api
    container_name: listings_api_prod
    depends_on:
      - postgres
      - redis
    ports:
      - "8000:8000"
    environment:
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_USER=${POSTGRES_USER}
      - DATABASE_PASSWORD=${POSTGRES_PASSWORD}
      - DATABASE_NAME=${POSTGRES_DB}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
      - ENVIRONMENT=production
      - DEBUG=false
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS}
    restart: unless-stopped

  listings-ingestion:
    build: 
      context: ./listings-service
    container_name: listings_ingestion_prod
    depends_on:
      - postgres
    volumes:
      - ./config.yml:/app/configs/config.yml
    environment:
      - RUN_ONCE=false
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data: