database:
  host: postgres
  port: 5432
  user: postgres
  password: password
  sslmode: disable

mls_systems:
  trreb:
    base_url: "https://query.ampre.ca/odata/"
    token: "eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ2ZW5kb3IvdHJyZWIvNzUyMiIsImF1ZCI6IkFtcFVzZXJzUHJkIiwicm9sZXMiOlsiQW1wVmVuZG9yIl0sImlzcyI6InByb2QuYW1wcmUuY2EiLCJleHAiOjI1MzQwMjMwMDc5OSwiaWF0IjoxNzQ1MzYxNjA0LCJzdWJqZWN0VHlwZSI6InZlbmRvciIsInN1YmplY3RLZXkiOiI3NTIyIiwianRpIjoiNjQ2ZDA5NjRiM2FiYWMzZiIsImN1c3RvbWVyTmFtZSI6InRycmViIn0.E2NInFQltEjQQgeQViDAhlrtoRw2WD8gdRFvhw9KT_8"
    database_name: "postgres"
    include_commercial: false
    active: true

ddf:
  token_url: "https://identity.crea.ca/connect/token"
  client_id: "ftiRfifept2pUDvyATYufdfp"
  client_secret: "mZhNBpf1a3WkZjkMzEwqsiBG"
  api_url: "https://ddfapi.realtor.ca/odata/v1"